# fly.toml app configuration file generated for polished-snow-8195 on 2023-11-14T09:45:18-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "polished-snow-8195"
primary_region = "ord"

[build]

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
