GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/6553ece96a47d87f85a47302

### Valid post test
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Josh Lakenan",
  "number": "269 779 2960"
}

### Duplicate Name error test
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Arto Hellas",
  "number": "269 779 2960"
}

### Missing name error test
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "number": "269 779 2960"
}